### ISSUE TITLE
bitcast <3 x i16> %x to <4 x i12>

### ISSUE THREAD

**Issue by aqjune** [snu-sf/llvm-freeze#21]
If `%x` is a vector `< i8 %a, i8 undef, i8 %c>`, and `%y = bitcast <3 x i8> %x to <4 x i6>`, then what is the second / third element of `%y`?

```
%x : [10101010|  undef  |10101010]
%y : [101010|  ?   |   ?  |101010]
```

According to our new semantics, the second / third element should be `undef`. We need to check whether there exist optimizations that are against new semantics.

**Comment by nunoplopes** [comment]
It is fine to transform undef in 0, for example, since it is just losing information.  So for those shuffles/folding, it's fine to pad numbers with zeros.  Probably that's what was already happening with the old undef?

**Comment by aqjune** [comment]
It has been almost 1 months since the last talk. 
I think padding numbers with zero would prevent removing bitcast-bitcast pairs in InstCombine.
For example, in this case :

```
; %x = [10101010|  undef  |10101010]
%y = bitcast <3 x i8> %x to <4 x i6> ; %y = [101010|100000|000010|101010]
%z = bitcast <4 x i6> %y to <3 x i8> ; %z = [10101010|00000000|10101010]
%vv = extractelement <3 x i8> %z, 1 ; (which is 0, but undef after optimization)
```

However, making whole bits `undef` (`%y = [101010|  undef   |   undef  |101010]`) also makes a problem. I found an example that is related to SROA.
For example, in this case : 

```
%t = alloca <8 x i16>
store <8 x i16> %x, <8 x i16>* %t
%t2 = bitcast <8 x i16>* %t to i32*
%v = load i32, i32* %t2
ret i32 %v
```

This is optimized into

```
%t.0.vec.extract = shufflevector <8 x i16> %x, <8 x i16> undef, <2 x i32> <i32 0, i32 1>
%1 = bitcast <2 x i16> %t.0.vec.extract to i32
ret i32 %1
```

(Though `%1` bitcasts from a vector to a scalar) If `%x = [0x1234 | undef | .... (6 more)]`, `%1` will be `undef`. So, we need to freeze `%t.0.vec.extract`, which is similar to the work done in C bitfield.

Therefore, both approaches seem to have a problem.

**Comment by aqjune** [comment]
I discussed with Hur, and for the SROA example, it is correct if `%v2 = load i32, i32* %t2` returns `undef`. Therefore, we don't need to add freeze after SROA optimization.

**Comment by nunoplopes** [comment]
Turning bits that were not undef into undef is absolutely wrong!
in your own example:

```
; %x = [10101010|  undef  |10101010]
%y = bitcast <3 x i8> %x to <4 x i6> ; %y = [101010|undef|undef|101010]
%z = bitcast <4 x i6> %y to <3 x i8> ; %z = [undef|undef|undef]
```

And this is totally wrong.  Doing this two bitcasts cannot lose information.

**Comment by nunoplopes** [comment]
I agree that the load %t2 can return undef.  Still doing a round of bitcasts cannot leave everything undef.

**Comment by alxest** [comment]
Dear @nunoplopes 

---

Would you please explain a bit more on this? Our team (including @gilhur) think it is reasonable semantics. I think making more things undef is more conservative, and If being not-undef is important in some optimization, one may freeze it before bitcast. 
I think being "undef" means more information, having more optimization chance, and concretizing undef into specific value means losing information, losing optimization chance.

In the example above, suppose there is an optimization concretizing %z into "%x". That itself is correct optimization. And after that, %z didn't lose any information compared to %x (exactly same). One may also concretize %z into suggested 0-padded form or whatever.

---

Concerning your comment here: https://github.com/snu-sf/llvm-freeze/issues/21#issuecomment-24006343
`so in theory instcombine can remove a 'bitcast of bitcast'.`

```
; %x = [10101010|  undef  |10101010]
%y = bitcast <3 x i8> %x to <4 x i6> ; %y = [101010|undef|undef|101010]
%z = bitcast <4 x i6> %y to <3 x i8> ; %z = [undef|undef|undef] 
```

(I just borrowed an example from right above.)
I understood your comment this way: Compiler should be able to replace all uses of %z with %x. (Which enables DCE of %z)
- If one defines "Padding the leftover bits with zeros" way, %z becomes [10101010|  00000000  |10101010]. Changing %z to %x essentially means changing [  00000000  ] to undef(i8). This is not correct.
- If one defines in "one undef bit means whole is undef" way, %z becomes [  undef  |  undef   |  undef  ]. Changing %z to %x is correct.

**Comment by nunoplopes** [comment]
Turning a defined bit into undef is illegal. Bitcast is not supposed to change any bit; at most it could convert an undef value into a concrete value.
It is possible to justify the removal of bitcast-of-bitcast if undef is defined per bit, instead of per word/value as we've been doing so far.

The option of making %z undef in all components is wrong.  See this example in C:

``` C++
int f() {
  int arr[3];
  arr[1] = 42;
  return ((int*)(char*)arr)[1];
}
```

does it return undef or 42?  It clearly has to return 42, but your suggestion of allowing bitcast to flip concrete bits into undef would break this.

Let me know if this isn't clear enough.

**Comment by nunoplopes** [comment]
Well, this example is not exactly as yours, because here the cast is between types whose sizes are a multiple of the other.  Not sure in C you can simulate non-power-of-two casts, though.
But still, the principle I was trying to convey is that casts are not supposed to introduce UB.  (they could in theory, but I guess that would be quite surprising to people)

**Comment by alxest** [comment]
Dear @nunoplopes 

---

For the first comment,
- While keeping "more-undef" semantics, problem you mentioned (even when non-power-of-two casts somehow exists in C) can be solved if we add freeze when compiling from C to LLVM IR.
- However, with "padding-0" semantics, freeze cannot rescue forementioned optimization.

Am I right? If so, we might need to investigate which one is more important.

My concern is "padding-0" semantics might disable many optimizations. For example, below is a random example from instcombine at first sight.

```
///   trunc (lshr (bitcast <4 x i32> %X to i128), 32) to i32
///   --->
///   extractelement <4 x i32> %X, 1
```

Suppose the 32 bits in interest is undef. 
In source, bitcasting will change these to 0. In target, these will remain undef.

---

For the second comment,
Um, I didn't exactly catch the reasoning behind that desire. Would you explain a bit more please?

**Comment by nunoplopes** [comment]
Your instcombine example is a good one.  You would like to obtain undef if the element you are interested in was originally undef.  I support that.
However, imagine that the element you were interested was not undef.  Then you cannot possibly have instcombine transforming something that is not undef into undef.
The problem in your example is that it transforms 4 values into 1. The question then is what to do if some of the 4 values was undef. Either we say that undef'ness is per value, and then all of the undef values have to become zero (you cannot change the value of non-undef things), or we say that undef'ness is per bit, and then we can do the transformation you mentioned.

Alternatively, if %X is frozen the optimization is correct with either semantics:

```
///   trunc (lshr (bitcast <4 x i32> %X to i128), 32) to i32
///   --->
///   extractelement (freeze <4 x i32> %X), 1
```

This is a bit sad, since it adds the overhead of freeze and breaks propagation of undef...

Maybe we really need some per-bit undef'ness semantics?  However, that would require changes everywhere else.  Like for comparison operators, a < b, is it undef if just one bit of a or b is undef?

**Comment by nunoplopes** [comment]
I'm just wondering about poison here..  It has exactly the same problem as our new undef..
I guess people were just ignoring it, or is there a way to justify this transformation with poison?

**Comment by alxest** [comment]
Dear @nunoplopes 

`However, imagine that the element you were interested was not undef. Then you cannot possibly have instcombine transforming something that is not undef into undef.`
Suppose 1 of these 4 is undef, and with our semantics
- The interested bits were undef: source gives undef, target gives undef, ok.
- The interested bits were non-undef: source gives undef, (because bitcasting spreads undef to whole value) target gives original non-undef, ok.
  I think it transforms undef into non-undef, so it is ok.

`The problem in your example is that it transforms 4 values into 1. The question then is what to do if some of the 4 values was undef. Either we say that undef'ness is per value, and then all of the undef values have to become zero (you cannot change the value of non-undef things), or we say that undef'ness is per bit, and then we can do the transformation you mentioned.`
My claim was that this is not true, because source gives 0 and target gives undef. 

In this example and above (@aqjune's example), we are thinking in opposite way somehow.
Maybe my understanding somewhere is totally wrong.
I suggest to keep it for the upcoming meeting.

`Alternatively, if %X is frozen the optimization is correct with either semantics:`
Ah, yes. I think you are obviously right.

`This is a bit sad, since it adds the overhead of freeze and breaks propagation of undef...`
Um, I am not very sure how this will affect performance. If this remains the only viable option, we might need to test it..

`Maybe we really need some per-bit undef'ness semantics? However, that would require changes everywhere else. Like for comparison operators, a < b, is it undef if just one bit of a or b is undef?`
- If you are right(our suggested semantics don't work), I agree we might need to think this option.
- `However, that would require changes everywhere else.` Um, would you explain a bit more please? Current LLVM's undef semantics is bitwise, and I think existing codes should make sense under bitwise semantics.
- Related question: How is this approach different from current LLVM's undef semantics? Is it going to be the same? I know current LLVM's undef semantics only in high level..
- Why was value-wise semantics preferred from bitwise-semantics? We might had discussion on it, but I couldn't recall it..
- On semantics: If value-wise semantics is somehow preferred, How about fit bitwise semantics into valuewise semantics? I mean, undef-ness **exists** bitwise, and is propagated bitwise during memory operations/gep/phi/bitcast/etc. But undef-ness **appears** value-wise, so in arithmetic operation (+,<,etc), for each operand(value), if at least one bit of it is undef, treat the whole value as undef and calculate it. a < b with somewhere one bit undef will result in undef of i1.

Thanks a lot.

**Comment by aqjune** [comment]
I think the term 'correctness' have different meanings between @nunoplopes and me/@alxest .
We say an optimization is correct if it satisfies 'refinement' ; After optimization (ex : removing a pair of bitcasts) if a set of possible behaviors of the code (@alxest said 'target') is a subset of possible bahaviors of code before optimization ('source'), then it holds refinement. If we define 'bitcast' as we did(changing adjacent bits into undef), then the refinement holds for eliminating a pair of bitcasts as well as InstCombine `trunc (lshr (bitcast <4 x i32> %X to i128), 32) to i32 -> extractelement ..`.

@alxest : To answer the fourth question (`Why was value-wise semantics preferred ..`), It is because our primary purpose is to remove `poison`. For an example, `%A = add nsw i32 2147483647, 1` is a poison value. Poison is not a bitwise concept (because 2147483647 < %A can be true), and what we want to do is now make `add nsw i32 2147483647, 1` `undef`, not `poison`.

As Nuno said, it has exactly the same problem in poison. If `poison` is not a bitwise concept, then what is the result of `bitcast <3 x i8> <10101010, poison, 101010> to <4 x i6>`? I also think that the problem I suggested is not a new one. It is similar to `computeKnownBits` problem.

I think @alxest 's suggestion (bitwise operation -> bitwise undef, arithmetic -> whole undef) is good. How do you think about it? One possible optimization we have to consider is like `icmp i32 %x, %y --> icmp i64 (((zext %x to i64) << 32) | %t), (((zext %y to i64) << 32) | %t)` (because if %x,%y is not `undef` and %t is `undef`, it can optimize `true`/`false` -> `undef`), but we can insert `freeze %t` . :)
